server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ludodb
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  jwtSecret: 65gfhjr682jhk84d65gfhjr682jhk84d65gfhjr682jhk84d
  jwtExpirationInMs: 86400000   # 1 day
  upload-dir: uploads/avatars   # ✅ avatar image storage path

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
