server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ludodb
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwtSecret: your-very-secret-key-which-should-be-very-long
  jwtExpirationInMs: 86400000   # 1 day

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
